export const SAVE_PERSONAL_FORM = "SAVE_PERSONAL_FORM";
export const SAVE_ESCOLAR_FORM = "SAVE_ESCOLAR_FORM";
export const SAVE_COMPANY_FORM = "SAVE_COMPANY_FORM";
export const INCREMENT_STEP = "INCREMENT_STEP";
export const DECREMENT_STEP = "DECREMENT_STEP";
