export const EXAMPLE_TEXT = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean blandit purus nec porta fringilla. Fusce nec nunc at tellus ultricies pulvinar sit amet vel erat. Nunc fringilla mauris id quam commodo dignissim. Sed fermentum tellus sed semper gravida. Etiam quis est vitae neque placerat hendrerit in non lacus. Cras purus lorem, iaculis sit amet tortor sit amet, blandit accumsan nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque luctus vehicula viverra. Nulla facilisi. Donec mattis nunc eget dolor semper, id venenatis urna luctus. Vivamus vulputate et velit ac mollis.

Quisque sed arcu at sapien faucibus efficitur vel ut felis. Vestibulum luctus non metus ut scelerisque. Quisque quis justo tortor. Nullam sodales odio a nunc placerat congue. Etiam vel sollicitudin odio. Morbi sit amet elementum sapien, eu congue risus. Curabitur hendrerit bibendum nisl. Fusce in pellentesque mauris.

Fusce faucibus efficitur enim, quis suscipit nulla rhoncus a. Nullam dui ante, mattis id ante ac, luctus malesuada elit. Duis eu lobortis felis, in malesuada nulla. Donec at interdum velit, id consectetur magna. Sed velit purus, maximus a felis vitae, blandit condimentum turpis. Morbi egestas quam at lacus efficitur, in vestibulum turpis rhoncus. Nullam placerat turpis libero, mattis semper arcu consequat ut. Donec vel est sed justo luctus bibendum eget sit amet diam.

Donec eget mattis metus. Phasellus ac iaculis erat, sit amet convallis felis. Ut vitae erat eget ex dictum cursus. Etiam ultricies nec enim a fermentum. Fusce ut tempor elit. Quisque gravida semper orci et feugiat. Integer vitae quam metus. Vivamus nec nulla in nisl ultrices hendrerit. Vestibulum porta aliquam porta. Donec facilisis, dolor a mollis volutpat, turpis lorem tincidunt nulla, vitae malesuada libero metus id sapien. Nam turpis augue, molestie vitae felis vel, tincidunt aliquet nibh. Nunc rutrum porta arcu quis mattis. Mauris ut lacus et sapien sagittis pretium. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Nullam elementum ut nisl in pellentesque. Aenean auctor tempor mi. Nunc quis eros nec augue facilisis interdum ut eget ligula. Pellentesque eget mauris a tellus finibus aliquet. Ut eget vulputate tortor. Donec vulputate erat vitae arcu accumsan euismod. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque pellentesque scelerisque sem, sit amet vehicula leo dapibus a. Ut in felis mi. Donec in risus enim. Aliquam egestas consequat congue. Suspendisse dapibus in justo vel auctor. Vestibulum a urna turpis. Mauris eu magna varius, suscipit risus ut, mattis sem.`;
